# Generated by Django 6.0 on 2025-12-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_course_material_choice_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentresult',
            options={},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Верный'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='score',
            field=models.IntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текстовый блок'), ('file', 'Файл/Медиа'), ('quiz', 'Тест')], max_length=10, verbose_name='Тип блока')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок блока')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='course_contents/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quiz', verbose_name='Связанный тест')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.course')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
