# Generated by Django 6.0 on 2026-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contentblock_options_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 — неограниченное количество попыток'),
        ),
    ]
