# Generated by Django 6.0 on 2026-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_is_multiple_quiz_shuffle_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Дата открытия курса. Пусто — доступен сразу.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Дата закрытия курса. Пусто — бессрочно.', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Дата открытия теста. Пусто — доступен сразу.', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Дата закрытия теста. Пусто — бессрочно.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Помечается автоматически если сдано после дедлайна'),
        ),
    ]
