# Generated by Django 6.0 on 2026-03-22 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_contentblock_lesson_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_code',
            field=models.CharField(blank=True, help_text='Код для самостоятельного подключения к курсу', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_self_enroll',
            field=models.BooleanField(default=False, help_text='Разрешить студентам подключаться по коду доступа'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
