# Generated by Django 6.0 on 2026-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_course_access_code_course_allow_self_enroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Ограничение по времени в минутах. Пусто — без ограничений.', null=True),
        ),
    ]
